trigger:
  branches:
    include:
      - main

pool:
  name: 'azure2agent'


stages:
- stage: Dev
  displayName: Deploy to dev
  jobs:
  - deployment: DeploytoDev
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Pipeline triggered from GitHub commit"
            displayName: 'Run sample script'
          - script: echo "deploying to dev"
- stage: QA
  displayName: Deploy to QA
  dependsOn: Dev
  jobs:
  - deployment: DeploytoQA
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "deploying to QA"
- stage: Prod
  displayName: Deploy to Prod
  dependsOn: QA
  jobs:
  - deployment: DeploytoProd
    environment: prod
    strategy: 
      runOnce:
        deploy:
          steps:
          - script: echo "deploying to Prod"

